#!/bin/bash
#set -euxo pipefail

rm -f /etc/machine-id ; dbus-uuidgen --ensure=/etc/machine-id

# 0. Insruqt init
#################

# waits for Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  sleep 1
done


# grant remote access
cat << EOF >> /root/.ssh/authorized_keys
${SSH_PUB_KEY}
EOF

echo "`python -c \"import socket; print(socket.gethostbyname('smlm'))\"` smlm.aaaaa.instruqt.io" >>/etc/hosts




nohup $( PROFILENAME='airco-dh4a-qa' SMLM_DNS="smlm.${_SANDBOX_ID}.instruqt.io" ACTIVATION_KEYS=1-liberty7ltss curl -Sks --retry 50 --retry-delay 5 --retry-max-time 180 "smlm.${_SANDBOX_ID}.instruqt.io"/pub/bootstrap/generic_bootstrap.sh | SMLM_DNS="smlm.${_SANDBOX_ID}.instruqt.io" ACTIVATION_KEYS=1-liberty7ltss PROFILENAME='airco-dh4a-qa' bash || echo 'failed' ) &
 

echo '###################### Completed zzcentos7 setup ###############
######################################################################'
shutdown -r 4 &
