#!/bin/bash

# fail early - fix earlier
#set -euxo pipefail

# Save the starting time
start_time=`date +%s`

rm -f /etc/machine-id ; dbus-uuidgen --ensure=/etc/machine-id



echo "# 0. Insruqt init
#################"

echo "# waits for Instruqt host bootstrap to finish"
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo -n .
  sleep 1
done

echo "# makes sure the registration is ok"
registercloudguest --force-new


## Get variables to instruqt
SSH_PRIVATE_KEY="$(agent variable get 'SSH_PRIVATE_KEY')"
SMLM_ADMIN_USERNAME="$(agent variable get 'SMLM_ADMIN_USERNAME')"
SMLM_ADMIN_PASSWORD="$(agent variable get 'SMLM_ADMIN_PASSWORD')"




# Create SSH config dir and pass the keys
cat << EOF > /root/.ssh/id_secret
$SSH_PRIVATE_KEY
EOF

echo "`python3 -c \"import socket; print(socket.gethostbyname('smlm'))\"` smlm.aaaaa.instruqt.io" >>/etc/hosts

echo "# 1. Initialize script
#################"

local_ip=`ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`

# Generate a random universal password for this student
UNIVERSAL_PWD="abcAB12.$(tr -dc '[:alnum:]' </dev/urandom | head -c 8; echo)"

# Generate organization name
ORG_ADM_USER="vega"
SMLM_ADMIN_USERNAME='myadmin'
FQDN_SMLM="smlm.${_SANDBOX_ID}.instruqt.io"
USER_ORG_NAME="trainning"


## Push variables to instruqt
agent variable set 'UNIVERSAL_PWD' "${UNIVERSAL_PWD}"
agent variable set 'FQDN_SMLM' "${FQDN_SMLM}"
agent variable set 'SMLM_URL' "https://$FQDN_SMLM"
agent variable set 'USER_ORG_NAME' "${USER_ORG_NAME}"
agent variable set 'SMLM_ADMIN_USERNAME' "${SMLM_ADMIN_USERNAME}"
agent variable set 'SMLM_ADMIN_PASSWORD' "${UNIVERSAL_PWD}"
agent variable set 'ORG_ADM_USER' "${ORG_ADM_USER}"



# setup dependencies
#zypper install -y python3-PyYAML 


# Configure remote SMLM
## Download the scripts

for i in manage_org.py manage_activationkeys.py manage_users.py manage_groups.py manage_custominfo.py manage_systems.py
do
  curl -skL --retry 40 --retry-delay 5 --retry-max-time 60 "${SMLM_SCRIPTS_URL}"/${i} > /usr/local/bin/${i} || echo "ERROR: Failed to retrieve ${SMLM_SCRIPTS_URL}/${i}"
  chmod a+x /usr/local/bin/${i}
  echo "Downloaded ${SMLM_SCRIPTS_URL}/${i}"
done



echo "# Waiting for SMLM to start"
curl -Sk --retry-connrefused --retry 40 --retry-delay 5 --retry-max-time 600 https://${FQDN_SMLM}/rhn/manager/api/api/getVersion || echo 'FAILLED! max timeout 180s reached trying to contact SMLM'



## Create admin user
manage_users.py -s "${FQDN_SMLM}" -u "${SMLM_ADMIN_USERNAME}" -p "${SMLM_ADMIN_PASSWORD}" --add --nusr ${SMLM_ADMIN_USERNAME} --npwd ${UNIVERSAL_PWD} --nrole satellite_admin,org_admin



## Create organization and user
manage_org.py -s "${FQDN_SMLM}" -u "${SMLM_ADMIN_USERNAME:-ERROR_empty}" -p "${SMLM_ADMIN_PASSWORD:-ERROR_empty}" \
  --add -o "${USER_ORG_NAME}" --admusr "${ORG_ADM_USER}" --admpwd "${UNIVERSAL_PWD}" \
  --admprefix 'Dr.' --admfirstname "${ORG_ADM_USER}" --admlastname user-instruqt \
  --admemail aaaa@aaa${_SANDBOX_ID}.org || echo "manage_org.py -s ${FQDN_SMLM} -u ${SMLM_ADMIN_USERNAME:-ERROR_empty} -p ${SMLM_ADMIN_PASSWORD:-ERROR_empty} --add -o ${USER_ORG_NAME} --admusr ${ORG_ADM_USER} --admpwd ${UNIVERSAL_PWD}  --admprefix 'Dr.' --admfirstname ${ORG_ADM_USER} --admlastname user-instruqt  --admemail aaaa@aaa${_SANDBOX_ID}.org"


for i in airtrain being cisne prod qa dev airco
do
  nohup $(while ! manage_groups.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}"  --group "${i}" -a  >/dev/null; do sleep 3; done) &
done

for i in "airtrain:at-ft-pro" "airtrain:at-ct-pro" "airtrain:at-ct-qa" "prod:at-ft-pro" "prod:at-ct-pro" "qa:at-ct-qa" "qa:airco-dh4a-qa" "airco:airco-dh4a-qa"
do
  nohup $(while ! manage_groups.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}"  --group "${i//:*}" -b --system "${i//*:}" >/dev/null; do sleep 5; done) &
done




nohup $(while ! manage_custominfo.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" -a --key application --description 'Main business application running on the system' >/dev/null; do sleep 5; done) &


for i in "at-ft-pro:fuselage systems" "at-ct-pro:controltech 2" "at-ct-qa:controltech 2" "airco-dh4a-qa:radio systems" 
do
  nohup $(while ! manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" --addcustomvalue --keyvalue "${i//*:}" --customkey application --system ${i//:*} >/dev/null ; do sleep 5; done) &
done


nohup $( timerr=0 ; while [[ "$timerr" -lt 50 ]]; do for i in `manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" -l | grep name: | awk '{print $2 }' | xargs`; do   manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" --system $i --schedulepackagerefresh >/dev/null; sleep 15; manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" --system $i --scheduleapplyhighstate >/dev/null; sleep 30; manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" --system $i --schedulehardwarerefresh  >/dev/null; sleep 15;  manage_systems.py -s "${FQDN_SMLM}"  -u "${SMLM_ADMIN_USERNAME}" -p "${UNIVERSAL_PWD}" --system $i --schedulestate >/dev/null;  done; sleep 50; ((timerr++)); done) &


echo '###################### Completed zbastion setup ################
######################################################################'
