#!/bin/bash
#set -euxo pipefail

rm -f /etc/machine-id ; dbus-uuidgen --ensure=/etc/machine-id

# 0. Insruqt init
#################

# waits for Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  sleep 1
done

# makes sure the registration is ok
registercloudguest --force-new


# grant remote access
cat << EOF >> /root/.ssh/authorized_keys
${SSH_PUB_KEY}
EOF

echo "`python3 -c \"import socket; print(socket.gethostbyname('smlm'))\"` smlm.aaaaa.instruqt.io" >>/etc/hosts


nohup $( curl -Sks --retry-connrefused --retry 50 --retry-delay 5 --retry-max-time 180 "smlm.${_SANDBOX_ID}.instruqt.io"/pub/bootstrap/generic_bootstrap.sh | HOSTNAME="smlm.${_SANDBOX_ID}.instruqt.io" ACTIVATION_KEYS=1-sles15sp6 PROFILENAME='ab-ft-pro'  bash || echo 'failed' ) &


echo '###################### Completed zzsles15a setup ###############
######################################################################'
shutdown -r 3 &
