version: "1"
virtualmachines:
- name: bastion
  image: suse/sles-15-sp6
  shell: /bin/bash
  machine_type: n1-standard-1
  allow_external_ingress:
  - high-ports
  - http
  - https
  environment:
    FQDN_SMLM: suma.not.known
secrets:
- name: SMLM_ADMIN_USERNAME
- name: SMLM_ADMIN_PASSWORD
- name: SSH_PRIVATE_KEY

