#!/bin/bash

# 0. Insruqt init
#################

# waits for Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  sleep 1
done

# makes sure the registration is ok
registercloudguest --force-new

# Create SSH config dir and pass the keys
[]
cat << EOF > /root/.ssh/id_secret
$SSH_PRIVATE_KEY
EOF

cat << EOF > /root/.ssh/config
Host $FQDN_SMLM
  User myuser
  IdentityFile /root/.ssh/id_secret
EOF


# Configure remote SMLM
## Create user

## Create org.

## Assign permissions





