version: "2"
virtualmachines:
- name: bastion
  image: suse/sles-15-sp6
  shell: /bin/bash
  environment:
    FQDN_SMLM: mlm-server.geeko.land
    SSL_PUB_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGk4PwwZ/cu+UNXhLB5LHUP6VDoHSKkFxW9NfUHV8LfG
    SMLM_USERNAME: mlmpilot1
    SMLM_PASSWORD: susemanager
    SMLM_ORGNAME: mynewtestorg
  machine_type: n1-standard-1
  allow_external_ingress:
  - high-ports
  - http
  - https
#- name: centos7
#  image: suse/dpv-centos7
#  shell: /bin/bash
#  environment:
#    FQDN_SMLM: mlm-server.geeko.land
#    SSL_PUB_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGk4PwwZ/cu+UNXhLB5LHUP6VDoHSKkFxW9NfUHV8LfG
#    SMLM_USERNAME: mlmpilot1
#    SMLM_PASSWORD: susemanager
#  machine_type: n1-standard-1
#  allow_external_ingress:
#  - high-ports
#  - http
#  - https
- name: sles15
  image: suse/sles-15-sp5
  shell: /bin/bash
  environment:
    FQDN_SMLM: mlm-server.geeko.land
    SSL_PUB_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGk4PwwZ/cu+UNXhLB5LHUP6VDoHSKkFxW9NfUHV8LfG
    SMLM_USERNAME: mlmpilot1
    SMLM_PASSWORD: susemanager
  machine_type: n1-standard-1
  allow_external_ingress:
  - high-ports
  - http
  - https

- name: ubuntu2404lts
  image: ubuntu-os-cloud/ubuntu-2404-lts-amd64
  shell: /bin/bash
  environment:
    FQDN_SMLM: mlm-server.geeko.land
    SSL_PUB_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGk4PwwZ/cu+UNXhLB5LHUP6VDoHSKkFxW9NfUHV8LfG
    SMLM_USERNAME: mlmpilot1
    SMLM_PASSWORD: susemanager
  machine_type: n1-standard-1
  allow_external_ingress:
  - high-ports
  - http
  - https

secrets:
- name: SMLM_ADMIN_USERNAME
- name: SMLM_ADMIN_PASSWORD
- name: SMLM_SSH_PRIVATE_KEY
